# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc22fee14c661b90ae8968e4badc6df46cb6c48f16b14c26df735314a1401d5b1e5af4a366b39576226b2e2df52eb83eb118a9fe75bb58588058a0718f47109a

test:
  secret_key_base: afef3a89f9bb4830290de45fb930c87f316ae49b0bc7f033fa7b85daad9cd433ee992ab11822f606a1a45ecefcd63bc8958309aeb47910d1ad6cafad58ab7656

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
